-- 1
SELECT B.*
FROM BOOKING B
WHERE DATEBOOKED LIKE '2021%'
ORDER BY EVENTMONTH ASC, EVENTDAY ASC

-- 2
SELECT B.TOURNAME 'tourname', C.GENDER 'gender', COUNT(B.DATEBOOKED) 'num bookings'
FROM CLIENT C
INNER JOIN BOOKING B
ON B.CLIENTID = C.CLIENTID
GROUP BY B.TOURNAME, C.GENDER
ORDER BY B.TOURNAME DESC

-- 3
SELECT B.TOURNAME 'tourname', C.GENDER 'gender', COUNT(B.DATEBOOKED) 'num bookings'
FROM CLIENT C
INNER JOIN BOOKING B
ON B.CLIENTID = C.CLIENTID
INNER JOIN [EVENT] E
ON E.TOURNAME = B.TOURNAME
AND E.EVENTMONTH = B.EVENTMONTH
AND E.EVENTDAY = B.EVENTDAY
AND E.EVENTYEAR = B.EVENTYEAR
WHERE E.EVENTMONTH = 'Feb'
GROUP BY C.GENDER, B.TOURNAME
HAVING COUNT(B.DATEBOOKED) < 2

-- 4
SELECT C.GIVENNAME, C.SURNAME, T.TOURNAME, T.DESCRIPTION, B.DATEBOOKED, E.EVENTFEE
FROM CLIENT C
INNER JOIN BOOKING B
ON B.CLIENTID = C.CLIENTID
INNER JOIN [EVENT] E
ON E.TOURNAME = B.TOURNAME
AND E.EVENTMONTH = B.EVENTMONTH
AND E.EVENTDAY = B.EVENTDAY
AND E.EVENTYEAR = B.EVENTYEAR
INNER JOIN TOUR T
ON T.TOURNAME = E.TOURNAME
WHERE E.EVENTMONTH = 'Jan'

-- 5
SELECT C.GIVENNAME, C.SURNAME, COUNT(B.CLIENTID)'NUM BOOKINGS'
FROM CLIENT C
LEFT JOIN BOOKING B
ON B.CLIENTID = C.CLIENTID
GROUP BY C.GIVENNAME, C.SURNAME, B.CLIENTID

-- 6
SELECT C.GIVENNAME, C.SURNAME, COUNT(B.CLIENTID)'NUM BOOKINGS'
FROM BOOKING B
RIGHT JOIN CLIENT C
ON C.CLIENTID = B.CLIENTID
GROUP BY C.GIVENNAME, C.SURNAME, B.CLIENTID

-- 7
SELECT C.*, E.*
FROM CLIENT C
FULL OUTER JOIN BOOKING B
ON B.CLIENTID = C.CLIENTID
FULL OUTER JOIN [EVENT] E
ON E.TOURNAME = B.TOURNAME
AND E.EVENTMONTH = B.EVENTMONTH
AND E.EVENTDAY = B.EVENTDAY
AND E.EVENTYEAR = B.EVENTYEAR

-- 8
SELECT C.CLIENTID
FROM CLIENT C
WHERE GENDER = 'F'

SELECT B.*
FROM BOOKING B
INNER JOIN CLIENT C
ON B.CLIENTID = C.CLIENTID
WHERE C.CLIENTID IN (SELECT C.CLIENTID
            FROM CLIENT C
            WHERE GENDER = 'F')

-- 9
SELECT C.GIVENNAME, C.SURNAME, E.EVENTFEE - B.PAYMENT 'AMOUNT OWING'
FROM CLIENT C
INNER JOIN BOOKING B
ON C.CLIENTID = B.CLIENTID
INNER JOIN [EVENT] E
ON E.TOURNAME = B.TOURNAME
AND E.EVENTMONTH = B.EVENTMONTH
AND E.EVENTDAY = B.EVENTDAY
AND E.EVENTYEAR = B.EVENTYEAR
WHERE E.EVENTFEE - B.PAYMENT > 0

-- 10
SELECT B.DATEBOOKED 'datebooked',
DATENAME(WEEKDAY, B.DATEBOOKED) 'DayOfWeek',
DATENAME(DAY, B.DATEBOOKED) 'DayOfMonth',
DATENAME(MONTH, B.DATEBOOKED) 'MonthName',
DATEPART(MONTH, B.DATEBOOKED) 'MonthNum',
DATENAME(YEAR, B.DATEBOOKED) 'Year'
FROM BOOKING B
